### ISSUE TITLE
How to include support for new language?

### ISSUE THREAD

**Issue by suyog-pipliwaal** [jordanorelli/.dotfiles#1]
Hey I am new to vim script and learning it. I want to configure vim to support multiple language so I stumble upon your vimrc and like your idea to create a individual file for each language keeping your vimrc clean. let say I want to support for c language or any other language in future. Please tell me how to do that and it would be great if you can show it with example. Thanks in advance.

**Comment by jordanorelli** [comment]
oh, uh, I don't really expect to get issues on this, it's just an archive of my own dotfiles; I don't expect other people to use it. But anyway the help topic you're looking for is "ftplugin", you can type `:help ftplugin` in vim and it'll open the documentation for ftplugin. But for C I'm pretty sure you'd just put your C-specific settings in `~/.vim/ftplugin/c.vim`. I don't really code C so I'm not sure what people actually do in practice.
